// ─────────────────────────────────────────────────────────────
//  Articulation zones — used by ArticulationDiagram
// ─────────────────────────────────────────────────────────────
export type MakhrajZone =
  | 'lips'        // شفتان  — ب م و ف
  | 'teeth_lip'   // أسنان+شفة — ف
  | 'interdental' // بين الأسنان — ث ذ ظ
  | 'alveolar'    // لثة — ت د ن ل ر
  | 'emphatic'    // لثوية مفخّمة — ص ض ط ظ
  | 'sibilant'    // صفير — س ز
  | 'palatal'     // حنك أوسط — ج ش ي
  | 'velar'       // حنك لين — ك
  | 'uvular'      // لهاة — ق غ خ
  | 'pharyngeal'  // حلق — ع ح
  | 'glottal'     // مزمار — ء ه
  | 'cavity'      // جوف — ا و ي (مد)

export interface ArabicLetter {
  letter: string
  name_ar: string
  name_en: string
  name_zh: string
  transliteration: string
  isolated: string
  initial: string
  medial: string
  final: string
  makhraj_zone: MakhrajZone
  makhraj_ar: string
  makhraj_zh: string
  makhraj_en: string
  similar_zh: string
  similar_en: string
  difficulty: 1 | 2 | 3
  is_emphatic: boolean
  no_chinese_equivalent: boolean
  example_word: string
  example_word_with_harakat: string
  example_meaning_en: string
  example_meaning_zh: string
  with_fatha: string
  with_damma: string
  with_kasra: string
  with_sukun: string
  tip_zh: string
}

export const ARABIC_ALPHABET: ArabicLetter[] = [
  {
    letter: 'ا', name_ar: 'ألف', name_en: 'Alef', name_zh: '阿里夫',
    transliteration: 'ā', isolated: 'ا', initial: 'ا', medial: 'ـا', final: 'ـا',
    makhraj_zone: 'cavity',
    makhraj_ar: 'الجوف — الفضاء الداخلي للفم والحلق',
    makhraj_zh: '口腔空腔 — 嘴巴张开，气流自由通过',
    makhraj_en: 'Open mouth cavity, free airflow',
    similar_zh: '啊 (ā) — 与拼音"a"相似，但略长',
    similar_en: 'Like "a" in "father"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'أب', example_word_with_harakat: 'أَبٌ',
    example_meaning_en: 'Father', example_meaning_zh: '父亲',
    with_fatha: 'اَ', with_damma: 'اُ', with_kasra: 'اِ', with_sukun: 'اْ',
    tip_zh: '嘴巴自然张开，发"啊"的长音。这是Arabic最基本的长元音。',
  },
  {
    letter: 'ب', name_ar: 'باء', name_en: 'Baa', name_zh: '巴',
    transliteration: 'b', isolated: 'ب', initial: 'بـ', medial: 'ـبـ', final: 'ـب',
    makhraj_zone: 'lips',
    makhraj_ar: 'الشفتان — انضمامهما ثم انفراجهما مع الصوت',
    makhraj_zh: '双唇音 — 双唇合拢后突然分开，同时振动声带',
    makhraj_en: 'Both lips pressed together then released with voice',
    similar_zh: '波 (bō) 中的b — 完全相同！',
    similar_en: '"b" in "book"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'بيت', example_word_with_harakat: 'بَيْتٌ',
    example_meaning_en: 'House', example_meaning_zh: '房子',
    with_fatha: 'بَ', with_damma: 'بُ', with_kasra: 'بِ', with_sukun: 'بْ',
    tip_zh: '与中文"波"的b完全相同！',
  },
  {
    letter: 'ت', name_ar: 'تاء', name_en: 'Taa', name_zh: '塔',
    transliteration: 't', isolated: 'ت', initial: 'تـ', medial: 'ـتـ', final: 'ـت',
    makhraj_zone: 'alveolar',
    makhraj_ar: 'طرف اللسان مع أصول الثنايا العليا',
    makhraj_zh: '舌尖抵上齿背，气流冲出，不送气',
    makhraj_en: 'Tongue tip against back of upper teeth, unaspirated',
    similar_zh: '特 (tè) 但不送气 — 类似"的"中的d更准确',
    similar_en: '"t" in "stop" (unaspirated)',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'تمر', example_word_with_harakat: 'تَمْرٌ',
    example_meaning_en: 'Dates (fruit)', example_meaning_zh: '椰枣',
    with_fatha: 'تَ', with_damma: 'تُ', with_kasra: 'تِ', with_sukun: 'تْ',
    tip_zh: '舌尖轻触上门牙背面，不送气。比中文"特"轻。',
  },
  {
    letter: 'ث', name_ar: 'ثاء', name_en: 'Thaa', name_zh: '萨（齿间）',
    transliteration: 'th', isolated: 'ث', initial: 'ثـ', medial: 'ـثـ', final: 'ـث',
    makhraj_zone: 'interdental',
    makhraj_ar: 'طرف اللسان بين الأسنان بدون صوت',
    makhraj_zh: '舌尖置于上下齿之间，气流通过，不振动声带',
    makhraj_en: 'Tongue tip between teeth, voiceless',
    similar_zh: '无对应音 — 类似英语"think"的th',
    similar_en: '"th" in "think" (voiceless)',
    difficulty: 2, is_emphatic: false, no_chinese_equivalent: true,
    example_word: 'ثلج', example_word_with_harakat: 'ثَلْجٌ',
    example_meaning_en: 'Snow / Ice', example_meaning_zh: '雪/冰',
    with_fatha: 'ثَ', with_damma: 'ثُ', with_kasra: 'ثِ', with_sukun: 'ثْ',
    tip_zh: '❗中文没有此音！伸出舌尖轻触上齿，呼气。类似英语"think"。',
  },
  {
    letter: 'ج', name_ar: 'جيم', name_en: 'Jiim', name_zh: '吉姆',
    transliteration: 'j', isolated: 'ج', initial: 'جـ', medial: 'ـجـ', final: 'ـج',
    makhraj_zone: 'palatal',
    makhraj_ar: 'وسط اللسان مع وسط الحنك الأعلى',
    makhraj_zh: '舌背抵硬腭中部，振动声带',
    makhraj_en: 'Middle of tongue against middle of hard palate',
    similar_zh: '家 (jiā) 中的j — 相似但更深沉',
    similar_en: '"j" in "jam"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'جمل', example_word_with_harakat: 'جَمَلٌ',
    example_meaning_en: 'Camel', example_meaning_zh: '骆驼',
    with_fatha: 'جَ', with_damma: 'جُ', with_kasra: 'جِ', with_sukun: 'جْ',
    tip_zh: '类似中文"家"的j，舌背抵硬腭，振动声带。',
  },
  {
    letter: 'ح', name_ar: 'حاء', name_en: 'Haa (pharyngeal)', name_zh: '哈（咽喉深）',
    transliteration: 'ḥ', isolated: 'ح', initial: 'حـ', medial: 'ـحـ', final: 'ـح',
    makhraj_zone: 'pharyngeal',
    makhraj_ar: 'وسط الحلق — احتكاك بدون صوت',
    makhraj_zh: '咽喉中部收缩，气流摩擦通过，声带不振动',
    makhraj_en: 'Mid-pharynx friction, voiceless',
    similar_zh: '无对应音 — 像对着镜子哈气，但从咽喉深处',
    similar_en: 'No English equivalent — deep breathy "h"',
    difficulty: 3, is_emphatic: false, no_chinese_equivalent: true,
    example_word: 'حب', example_word_with_harakat: 'حُبٌّ',
    example_meaning_en: 'Love', example_meaning_zh: '爱',
    with_fatha: 'حَ', with_damma: 'حُ', with_kasra: 'حِ', with_sukun: 'حْ',
    tip_zh: '❗最难音之一！咽喉收紧，像呼吸雾气"哈"，但更深，声带不振动。练习：手放喉咙，感觉无振动。',
  },
  {
    letter: 'خ', name_ar: 'خاء', name_en: 'Khaa', name_zh: '哈（软腭）',
    transliteration: 'kh', isolated: 'خ', initial: 'خـ', medial: 'ـخـ', final: 'ـخ',
    makhraj_zone: 'uvular',
    makhraj_ar: 'أدنى الحلق — اللهاة مع أقصى اللسان، بدون صوت',
    makhraj_zh: '软腭后部摩擦，声带不振动',
    makhraj_en: 'Uvular friction, voiceless',
    similar_zh: '类似"喝"但从软腭深处，有摩擦感',
    similar_en: '"ch" in German "Bach"',
    difficulty: 2, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'خبز', example_word_with_harakat: 'خُبْزٌ',
    example_meaning_en: 'Bread', example_meaning_zh: '面包',
    with_fatha: 'خَ', with_damma: 'خُ', with_kasra: 'خِ', with_sukun: 'خْ',
    tip_zh: '发"喝"，把位置往后推到软腭，产生摩擦。像轻轻漱口的声音。',
  },
  {
    letter: 'د', name_ar: 'دال', name_en: 'Daal', name_zh: '达尔',
    transliteration: 'd', isolated: 'د', initial: 'د', medial: 'ـد', final: 'ـد',
    makhraj_zone: 'alveolar',
    makhraj_ar: 'طرف اللسان مع أصول الثنايا العليا مع الصوت',
    makhraj_zh: '舌尖抵上齿背，振动声带',
    makhraj_en: 'Tongue tip against upper teeth, voiced',
    similar_zh: '的 (de) 中的d — 基本相同',
    similar_en: '"d" in "door"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'دار', example_word_with_harakat: 'دَارٌ',
    example_meaning_en: 'Home', example_meaning_zh: '家',
    with_fatha: 'دَ', with_damma: 'دُ', with_kasra: 'دِ', with_sukun: 'دْ',
    tip_zh: '与中文"的"中d音相同，振动声带。',
  },
  {
    letter: 'ذ', name_ar: 'ذال', name_en: 'Dhaal', name_zh: '扎尔（齿间浊）',
    transliteration: 'dh', isolated: 'ذ', initial: 'ذ', medial: 'ـذ', final: 'ـذ',
    makhraj_zone: 'interdental',
    makhraj_ar: 'طرف اللسان بين الأسنان مع الصوت',
    makhraj_zh: '舌尖置于上下齿之间，振动声带',
    makhraj_en: 'Tongue between teeth, voiced',
    similar_zh: '无对应音 — 类似英语"the"的th',
    similar_en: '"th" in "the" (voiced)',
    difficulty: 2, is_emphatic: false, no_chinese_equivalent: true,
    example_word: 'ذهب', example_word_with_harakat: 'ذَهَبٌ',
    example_meaning_en: 'Gold / He went', example_meaning_zh: '金子/他去了',
    with_fatha: 'ذَ', with_damma: 'ذُ', with_kasra: 'ذِ', with_sukun: 'ذْ',
    tip_zh: '❗中文没有此音！与ث同位置，加声带振动。类似英语"the"。',
  },
  {
    letter: 'ر', name_ar: 'راء', name_en: 'Raa', name_zh: '拉（颤音）',
    transliteration: 'r', isolated: 'ر', initial: 'ر', medial: 'ـر', final: 'ـر',
    makhraj_zone: 'alveolar',
    makhraj_ar: 'طرف اللسان مع اللثة — تكرار',
    makhraj_zh: '舌尖轻弹齿龈，产生颤音（1-2次）',
    makhraj_en: 'Tongue tip tapping alveolar ridge, slight trill',
    similar_zh: '类似西班牙语r，舌尖快速弹动',
    similar_en: 'Like Spanish "r" in "pero"',
    difficulty: 2, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'رجل', example_word_with_harakat: 'رَجُلٌ',
    example_meaning_en: 'Man', example_meaning_zh: '男人',
    with_fatha: 'رَ', with_damma: 'رُ', with_kasra: 'رِ', with_sukun: 'رْ',
    tip_zh: '舌尖轻弹齿龈1-2次。比中文r更靠前，像摩托车轻微发动的感觉。',
  },
  {
    letter: 'ز', name_ar: 'زاي', name_en: 'Zaay', name_zh: '扎',
    transliteration: 'z', isolated: 'ز', initial: 'ز', medial: 'ـز', final: 'ـز',
    makhraj_zone: 'sibilant',
    makhraj_ar: 'طرف اللسان قرب اللثة — احتكاك مع صوت',
    makhraj_zh: '舌尖接近上齿龈，气流嗡嗡振动声带',
    makhraj_en: 'Tongue near alveolar ridge, voiced sibilant',
    similar_zh: '资 (zī) 的z但振动声带 — 或英语"zoo"',
    similar_en: '"z" in "zero"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'زيت', example_word_with_harakat: 'زَيْتٌ',
    example_meaning_en: 'Olive oil', example_meaning_zh: '橄榄油',
    with_fatha: 'زَ', with_damma: 'زُ', with_kasra: 'زِ', with_sukun: 'زْ',
    tip_zh: '类似中文"资"的z，但加声带振动，产生嗡嗡的z音。',
  },
  {
    letter: 'س', name_ar: 'سين', name_en: 'Siin', name_zh: '辛（细s）',
    transliteration: 's', isolated: 'س', initial: 'سـ', medial: 'ـسـ', final: 'ـس',
    makhraj_zone: 'sibilant',
    makhraj_ar: 'طرف اللسان قرب اللثة — احتكاك بدون صوت',
    makhraj_zh: '舌尖接近上齿龈，气流嘶嘶，不振动声带',
    makhraj_en: 'Tongue near alveolar ridge, voiceless sibilant',
    similar_zh: '思 (sī) 中的s — 完全相同！注意区别ص（粗s）',
    similar_en: '"s" in "sun"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'سماء', example_word_with_harakat: 'سَمَاءٌ',
    example_meaning_en: 'Sky', example_meaning_zh: '天空',
    with_fatha: 'سَ', with_damma: 'سُ', with_kasra: 'سِ', with_sukun: 'سْ',
    tip_zh: '与中文"思"的s完全相同！重要：س是细音，ص是粗音，区别很大！',
  },
  {
    letter: 'ش', name_ar: 'شين', name_en: 'Shiin', name_zh: '申',
    transliteration: 'sh', isolated: 'ش', initial: 'شـ', medial: 'ـشـ', final: 'ـش',
    makhraj_zone: 'palatal',
    makhraj_ar: 'وسط اللسان مع الحنك — احتكاك بدون صوت',
    makhraj_zh: '舌背抵硬腭，嘴唇略圆，发"嘘"音',
    makhraj_en: 'Tongue body raised to hard palate, voiceless',
    similar_zh: '诗 (shī) 中的sh — 完全相同！',
    similar_en: '"sh" in "she"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'شمس', example_word_with_harakat: 'شَمْسٌ',
    example_meaning_en: 'Sun', example_meaning_zh: '太阳',
    with_fatha: 'شَ', with_damma: 'شُ', with_kasra: 'شِ', with_sukun: 'شْ',
    tip_zh: '与中文"诗"的sh完全相同！',
  },
  {
    letter: 'ص', name_ar: 'صاد', name_en: 'Saad (emphatic)', name_zh: '萨德（粗s）',
    transliteration: 'ṣ', isolated: 'ص', initial: 'صـ', medial: 'ـصـ', final: 'ـص',
    makhraj_zone: 'emphatic',
    makhraj_ar: 'طرف اللسان قرب اللثة مع تفخيم',
    makhraj_zh: '与س同位置，但舌根上抬，口腔变厚，声音变"粗"',
    makhraj_en: 'Same as س but pharyngealized (tongue root raised)',
    similar_zh: '无对应音 — 像"思"但舌根上抬，声音变沉',
    similar_en: 'No English equivalent — pharyngealized "s"',
    difficulty: 3, is_emphatic: true, no_chinese_equivalent: true,
    example_word: 'صباح', example_word_with_harakat: 'صَبَاحٌ',
    example_meaning_en: 'Morning', example_meaning_zh: '早晨',
    with_fatha: 'صَ', with_damma: 'صُ', with_kasra: 'صِ', with_sukun: 'صْ',
    tip_zh: '❗中文无此音！发"思"时，同时把舌根往上抬，嘴巴空间变小，声音变粗沉。这叫"粗音"مفخّم。',
  },
  {
    letter: 'ض', name_ar: 'ضاد', name_en: 'Daad (emphatic)', name_zh: '达德（粗d）',
    transliteration: 'ḍ', isolated: 'ض', initial: 'ضـ', medial: 'ـضـ', final: 'ـض',
    makhraj_zone: 'emphatic',
    makhraj_ar: 'حافة اللسان مع الأضراس مع التفخيم',
    makhraj_zh: '与د同位置，加上舌根上抬产生粗音',
    makhraj_en: 'Pharyngealized "d", lateral tongue contact',
    similar_zh: '无对应音 — 像"的"但舌根上抬，声音变粗',
    similar_en: 'No English equivalent — pharyngealized "d"',
    difficulty: 3, is_emphatic: true, no_chinese_equivalent: true,
    example_word: 'ضوء', example_word_with_harakat: 'ضَوْءٌ',
    example_meaning_en: 'Light', example_meaning_zh: '光',
    with_fatha: 'ضَ', with_damma: 'ضُ', with_kasra: 'ضِ', with_sukun: 'ضْ',
    tip_zh: '❗Arabic的独特音！阿拉伯语被称为"ضاد之语"。发"的"时，同时把舌根上抬，声音变沉厚。',
  },
  {
    letter: 'ط', name_ar: 'طاء', name_en: 'Taa (emphatic)', name_zh: '塔（粗t）',
    transliteration: 'ṭ', isolated: 'ط', initial: 'طـ', medial: 'ـطـ', final: 'ـط',
    makhraj_zone: 'emphatic',
    makhraj_ar: 'طرف اللسان مع اللثة مع التفخيم',
    makhraj_zh: '与ت同位置，加上舌根上抬产生粗音',
    makhraj_en: 'Same position as ت, pharyngealized',
    similar_zh: '无对应音 — 像"特"但舌根上抬，更圆厚',
    similar_en: 'No English equivalent — pharyngealized "t"',
    difficulty: 3, is_emphatic: true, no_chinese_equivalent: true,
    example_word: 'طفل', example_word_with_harakat: 'طِفْلٌ',
    example_meaning_en: 'Child', example_meaning_zh: '孩子',
    with_fatha: 'طَ', with_damma: 'طُ', with_kasra: 'طِ', with_sukun: 'طْ',
    tip_zh: '发"特"，但舌根上抬，嘴唇稍圆，声音变圆厚低沉。',
  },
  {
    letter: 'ظ', name_ar: 'ظاء', name_en: 'Dhaa (emphatic)', name_zh: '扎（粗齿间）',
    transliteration: 'ẓ', isolated: 'ظ', initial: 'ظـ', medial: 'ـظـ', final: 'ـظ',
    makhraj_zone: 'emphatic',
    makhraj_ar: 'طرف اللسان بين الأسنان مع التفخيم والصوت',
    makhraj_zh: '与ذ同位置（舌尖伸出），加上舌根上抬',
    makhraj_en: 'Emphatic interdental, voiced',
    similar_zh: '无对应音 — 最复杂组合：齿间+粗音+声带',
    similar_en: 'No equivalent — emphatic voiced "th"',
    difficulty: 3, is_emphatic: true, no_chinese_equivalent: true,
    example_word: 'ظهر', example_word_with_harakat: 'ظَهْرٌ',
    example_meaning_en: 'Back / Noon', example_meaning_zh: '背部/中午',
    with_fatha: 'ظَ', with_damma: 'ظُ', with_kasra: 'ظِ', with_sukun: 'ظْ',
    tip_zh: '❗最难音之一！舌尖伸到上下齿之间 + 舌根上抬 + 声带振动。三重组合。',
  },
  {
    letter: 'ع', name_ar: 'عين', name_en: 'ʿAyn', name_zh: '阿因（咽喉浊）',
    transliteration: 'ʿ', isolated: 'ع', initial: 'عـ', medial: 'ـعـ', final: 'ـع',
    makhraj_zone: 'pharyngeal',
    makhraj_ar: 'وسط الحلق — تضييق الحلق مع الصوت',
    makhraj_zh: '咽喉中部强力收缩，振动声带，产生"挤压感"',
    makhraj_en: 'Mid-pharynx voiced fricative',
    similar_zh: '无任何对应音 — 发"啊"时用力挤压咽喉',
    similar_en: 'No equivalent in any European language',
    difficulty: 3, is_emphatic: false, no_chinese_equivalent: true,
    example_word: 'عين', example_word_with_harakat: 'عَيْنٌ',
    example_meaning_en: 'Eye / Spring', example_meaning_zh: '眼睛/泉水',
    with_fatha: 'عَ', with_damma: 'عُ', with_kasra: 'عِ', with_sukun: 'عْ',
    tip_zh: '❗最难音之一！咽喉收缩发"啊"，像被吓到时喉咙收紧。把手放喉咙感受振动。每天练习！',
  },
  {
    letter: 'غ', name_ar: 'غين', name_en: 'Ghayn', name_zh: '加因（软腭浊）',
    transliteration: 'gh', isolated: 'غ', initial: 'غـ', medial: 'ـغـ', final: 'ـغ',
    makhraj_zone: 'uvular',
    makhraj_ar: 'أدنى الحلق — اللهاة مع الصوت',
    makhraj_zh: '软腭后部（悬雍垂）摩擦，振动声带',
    makhraj_en: 'Voiced uvular fricative (like French r)',
    similar_zh: '类似法语r音（巴黎的r），或漱口加声带振动',
    similar_en: 'Like French "r" in "Paris"',
    difficulty: 2, is_emphatic: false, no_chinese_equivalent: true,
    example_word: 'غرفة', example_word_with_harakat: 'غُرْفَةٌ',
    example_meaning_en: 'Room', example_meaning_zh: '房间',
    with_fatha: 'غَ', with_damma: 'غُ', with_kasra: 'غِ', with_sukun: 'غْ',
    tip_zh: '像漱口的声音加声带振动。把خ（无声）加声带振动 = غ。',
  },
  {
    letter: 'ف', name_ar: 'فاء', name_en: 'Faa', name_zh: '法',
    transliteration: 'f', isolated: 'ف', initial: 'فـ', medial: 'ـفـ', final: 'ـف',
    makhraj_zone: 'teeth_lip',
    makhraj_ar: 'باطن الشفة السفلى مع أطراف الثنايا العليا',
    makhraj_zh: '下唇内侧轻触上门牙，气流通过，不振动声带',
    makhraj_en: 'Inner lower lip against upper front teeth, voiceless',
    similar_zh: '飞 (fēi) 中的f — 完全相同！',
    similar_en: '"f" in "fan"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'فيل', example_word_with_harakat: 'فِيلٌ',
    example_meaning_en: 'Elephant', example_meaning_zh: '大象',
    with_fatha: 'فَ', with_damma: 'فُ', with_kasra: 'فِ', with_sukun: 'فْ',
    tip_zh: '与中文"飞"的f完全相同！',
  },
  {
    letter: 'ق', name_ar: 'قاف', name_en: 'Qaaf', name_zh: '卡夫（最深爆破）',
    transliteration: 'q', isolated: 'ق', initial: 'قـ', medial: 'ـقـ', final: 'ـق',
    makhraj_zone: 'uvular',
    makhraj_ar: 'أقصى اللسان مع اللهاة — انفجار عميق',
    makhraj_zh: '舌根抵悬雍垂（小舌），猛然分开产生爆破音',
    makhraj_en: 'Back of tongue against uvula, uvular stop',
    similar_zh: '无对应音 — 比"喀"的k更靠后，发自最深处',
    similar_en: 'No equivalent — deeper than "k"',
    difficulty: 2, is_emphatic: false, no_chinese_equivalent: true,
    example_word: 'قلب', example_word_with_harakat: 'قَلْبٌ',
    example_meaning_en: 'Heart', example_meaning_zh: '心脏',
    with_fatha: 'قَ', with_damma: 'قُ', with_kasra: 'قِ', with_sukun: 'قْ',
    tip_zh: '发"喀"，把位置推到舌根最深处（小舌位置）。感受喉咙深处爆破感。ق比ك更深！',
  },
  {
    letter: 'ك', name_ar: 'كاف', name_en: 'Kaaf', name_zh: '卡夫（软腭）',
    transliteration: 'k', isolated: 'ك', initial: 'كـ', medial: 'ـكـ', final: 'ـك',
    makhraj_zone: 'velar',
    makhraj_ar: 'أقصى اللسان مع الحنك اللين',
    makhraj_zh: '舌背后部抵软腭，猛然分开，不送气',
    makhraj_en: 'Back of tongue against soft palate, unaspirated',
    similar_zh: '喀 (kā) 但不送气 — 类似"个"的g',
    similar_en: '"k" in "skin" (unaspirated)',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'كتاب', example_word_with_harakat: 'كِتَابٌ',
    example_meaning_en: 'Book', example_meaning_zh: '书',
    with_fatha: 'كَ', with_damma: 'كُ', with_kasra: 'كِ', with_sukun: 'كْ',
    tip_zh: '类似中文"个"的g，舌背轻触软腭，不送气。',
  },
  {
    letter: 'ل', name_ar: 'لام', name_en: 'Laam', name_zh: '拉姆',
    transliteration: 'l', isolated: 'ل', initial: 'لـ', medial: 'ـلـ', final: 'ـل',
    makhraj_zone: 'alveolar',
    makhraj_ar: 'طرف اللسان مع اللثة — جانبي مع صوت',
    makhraj_zh: '舌尖抵上齿龈，气流从舌两侧流出',
    makhraj_en: 'Tongue tip on alveolar ridge, lateral',
    similar_zh: '乐 (lè) 中的l — 基本相同！',
    similar_en: '"l" in "love"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'لغة', example_word_with_harakat: 'لُغَةٌ',
    example_meaning_en: 'Language', example_meaning_zh: '语言',
    with_fatha: 'لَ', with_damma: 'لُ', with_kasra: 'لِ', with_sukun: 'لْ',
    tip_zh: '与中文"乐"的l基本相同。注意：لله(الله)中的ل是特殊粗音。',
  },
  {
    letter: 'م', name_ar: 'ميم', name_en: 'Miim', name_zh: '米姆',
    transliteration: 'm', isolated: 'م', initial: 'مـ', medial: 'ـمـ', final: 'ـم',
    makhraj_zone: 'lips',
    makhraj_ar: 'الشفتان — انضمامهما مع صوت أنفي',
    makhraj_zh: '双唇合拢，气流从鼻腔通过，振动声带',
    makhraj_en: 'Both lips closed, nasal resonance',
    similar_zh: '妈 (mā) 中的m — 完全相同！',
    similar_en: '"m" in "moon"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'ماء', example_word_with_harakat: 'مَاءٌ',
    example_meaning_en: 'Water', example_meaning_zh: '水',
    with_fatha: 'مَ', with_damma: 'مُ', with_kasra: 'مِ', with_sukun: 'مْ',
    tip_zh: '与中文"妈"的m完全相同！',
  },
  {
    letter: 'ن', name_ar: 'نون', name_en: 'Nuun', name_zh: '努恩',
    transliteration: 'n', isolated: 'ن', initial: 'نـ', medial: 'ـنـ', final: 'ـن',
    makhraj_zone: 'alveolar',
    makhraj_ar: 'طرف اللسان مع اللثة مع صوت أنفي',
    makhraj_zh: '舌尖抵上齿龈，气流从鼻腔通过',
    makhraj_en: 'Tongue tip on alveolar ridge, nasal',
    similar_zh: '那 (nà) 中的n — 完全相同！',
    similar_en: '"n" in "noon"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'نور', example_word_with_harakat: 'نُورٌ',
    example_meaning_en: 'Light', example_meaning_zh: '光',
    with_fatha: 'نَ', with_damma: 'نُ', with_kasra: 'نِ', with_sukun: 'نْ',
    tip_zh: '与中文"那"的n完全相同！',
  },
  {
    letter: 'ه', name_ar: 'هاء', name_en: 'Haa (glottal)', name_zh: '哈（声门轻）',
    transliteration: 'h', isolated: 'ه', initial: 'هـ', medial: 'ـهـ', final: 'ـه',
    makhraj_zone: 'glottal',
    makhraj_ar: 'أقصى الحلق — المزمار — هواء لطيف',
    makhraj_zh: '声门处轻柔呼气，无摩擦，声带不振动',
    makhraj_en: 'Gentle glottal breath, no friction',
    similar_zh: '哈 (hā) 但更轻更柔 — 像轻轻呼气',
    similar_en: '"h" in "house"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'هواء', example_word_with_harakat: 'هَوَاءٌ',
    example_meaning_en: 'Air / Wind', example_meaning_zh: '空气',
    with_fatha: 'هَ', with_damma: 'هُ', with_kasra: 'هِ', with_sukun: 'هْ',
    tip_zh: '比中文"哈"更轻柔，像对着镜子呵气。注意：与ح(深)完全不同！ه很轻，ح很重。',
  },
  {
    letter: 'و', name_ar: 'واو', name_en: 'Waaw', name_zh: '瓦乌',
    transliteration: 'w / ū', isolated: 'و', initial: 'و', medial: 'ـو', final: 'ـو',
    makhraj_zone: 'lips',
    makhraj_ar: 'الشفتان مستديرتان — حرف ومد',
    makhraj_zh: '双唇圆收，可作辅音(w)或长元音(ū)',
    makhraj_en: 'Rounded lips, consonant (w) or long vowel (ū)',
    similar_zh: '乌 (wū) 中的w — 基本相同！',
    similar_en: '"w" in "water"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'وردة', example_word_with_harakat: 'وَرْدَةٌ',
    example_meaning_en: 'Rose', example_meaning_zh: '玫瑰',
    with_fatha: 'وَ', with_damma: 'وُ', with_kasra: 'وِ', with_sukun: 'وْ',
    tip_zh: '双重功能：辅音w（如"乌"）或长元音ū（如"屋"）。嘴唇圆收。',
  },
  {
    letter: 'ي', name_ar: 'ياء', name_en: 'Yaa', name_zh: '雅',
    transliteration: 'y / ī', isolated: 'ي', initial: 'يـ', medial: 'ـيـ', final: 'ـي',
    makhraj_zone: 'palatal',
    makhraj_ar: 'وسط اللسان مع الحنك — حرف ومد',
    makhraj_zh: '舌背抵硬腭，可作辅音(y)或长元音(ī)',
    makhraj_en: 'Middle tongue to palate, consonant (y) or long vowel (ī)',
    similar_zh: '一 (yī) 中的y — 完全相同！',
    similar_en: '"y" in "yes"',
    difficulty: 1, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'يد', example_word_with_harakat: 'يَدٌ',
    example_meaning_en: 'Hand', example_meaning_zh: '手',
    with_fatha: 'يَ', with_damma: 'يُ', with_kasra: 'يِ', with_sukun: 'يْ',
    tip_zh: '双重功能：辅音y（如"一"）或长元音ī（如"衣"）。',
  },
  {
    letter: 'ء', name_ar: 'همزة', name_en: 'Hamza', name_zh: '喉塞音',
    transliteration: 'ʾ', isolated: 'ء', initial: 'أ/إ', medial: 'ئـ/ؤ', final: 'ء',
    makhraj_zone: 'glottal',
    makhraj_ar: 'المزمار — إغلاق الوترين الصوتيين ثم فتحهما',
    makhraj_zh: '声门完全关闭后突然打开，产生短暂停顿感',
    makhraj_en: 'Complete glottal closure then release',
    similar_zh: '类似北京话"啊一啊"中间的停顿感',
    similar_en: 'Like the catch in "uh-oh"',
    difficulty: 2, is_emphatic: false, no_chinese_equivalent: false,
    example_word: 'أب', example_word_with_harakat: 'أَبٌ',
    example_meaning_en: 'Father', example_meaning_zh: '父亲',
    with_fatha: 'أَ', with_damma: 'أُ', with_kasra: 'إِ', with_sukun: 'أْ',
    tip_zh: '说"啊"前停顿一下，声门先关后开。英语"uh-oh"中间的感觉。常写在ا、و、ي上面。',
  },
]

// ─────────────────────────────────────────────────────────────
//  Harakat — حركات (diacritics / vowel marks)
// ─────────────────────────────────────────────────────────────
export interface Haraka {
  id: string
  symbol: string
  name_ar: string
  name_zh: string
  name_en: string
  sound_zh: string
  sound_en: string
  example_with_ba: string
  example_word: string
  example_word_with_harakat: string
  example_transliteration: string
  example_meaning_zh: string
  example_meaning_en: string
  position: 'above' | 'below' | 'above_double' | 'below_double'
  tip_zh: string
  color: string
  memory_trick_zh: string   // visual/mnemonic trick for Chinese students
}

export const HARAKAT: Haraka[] = [
  {
    id: 'fatha',
    symbol: 'َ',
    name_ar: 'فَتْحة',
    name_zh: '法特哈 فَتْحة（开口符）',
    name_en: 'Fatha',
    sound_zh: '短"啊"音 — 嘴巴微张，快速收回',
    sound_en: 'Short "a" as in "can"',
    example_with_ba: 'بَ',
    example_word: 'كتب',
    example_word_with_harakat: 'كَتَبَ',
    example_transliteration: 'ka-ta-ba',
    example_meaning_zh: '他写了',
    example_meaning_en: 'He wrote',
    position: 'above',
    tip_zh: '写在字母【上方】，像一个小斜线 ◌َ。发短"啊"，不拉长。\n例：بَ = "ba"，كَ = "ka"，مَ = "ma"',
    color: '#3B82F6',
    memory_trick_zh: '记忆法：فَتْحة = "开口"，嘴巴向下开，斜线也向下斜 ╲',
  },
  {
    id: 'damma',
    symbol: 'ُ',
    name_ar: 'ضَمَّة',
    name_zh: '达玛 ضَمَّة（圆唇符）',
    name_en: 'Damma',
    sound_zh: '短"乌"音 — 嘴唇圆收，快速收回',
    sound_en: 'Short "u" as in "put"',
    example_with_ba: 'بُ',
    example_word: 'كتب',
    example_word_with_harakat: 'كُتُبٌ',
    example_transliteration: 'ku-tu-bun',
    example_meaning_zh: '书（复数）',
    example_meaning_en: 'Books',
    position: 'above',
    tip_zh: '写在字母【上方】，形状像小واو ◌ُ。发短"乌"，嘴唇稍圆。\n例：بُ = "bu"，كُ = "ku"，مُ = "mu"',
    color: '#10B981',
    memory_trick_zh: '记忆法：ضَمَّة = "圆拢"，符号形似小圆钩，嘴唇也圆 ◌',
  },
  {
    id: 'kasra',
    symbol: 'ِ',
    name_ar: 'كَسْرة',
    name_zh: '卡斯拉 كَسْرة（下破符）',
    name_en: 'Kasra',
    sound_zh: '短"衣"音 — 嘴唇横张，快速收回',
    sound_en: 'Short "i" as in "bit"',
    example_with_ba: 'بِ',
    example_word: 'بئر',
    example_word_with_harakat: 'بِئْرٌ',
    example_transliteration: 'bi-ʾrun',
    example_meaning_zh: '水井',
    example_meaning_en: 'Well',
    position: 'below',
    tip_zh: '写在字母【下方】，像一个小斜线在下面 ◌ِ。发短"衣"，嘴唇横张。\n例：بِ = "bi"，كِ = "ki"，مِ = "mi"',
    color: '#F59E0B',
    memory_trick_zh: '记忆法：كَسْرة = "断裂"，符号在下方折断，嘴角向两侧拉开 ←→',
  },
  {
    id: 'sukun',
    symbol: 'ْ',
    name_ar: 'سُكون',
    name_zh: '苏孔 سُكون（静音符）',
    name_en: 'Sukun',
    sound_zh: '无元音 — 字母只发辅音，停止气流',
    sound_en: 'No vowel — consonant only, stop airflow',
    example_with_ba: 'بْ',
    example_word: 'بيت',
    example_word_with_harakat: 'بَيْتٌ',
    example_transliteration: 'bayt',
    example_meaning_zh: '房子（يْ无元音，只发y）',
    example_meaning_en: 'House',
    position: 'above',
    tip_zh: '写在字母【上方】，形如小圆圈 ◌ْ。该字母无元音，只发辅音后停止。\n例：بَيْتٌ "bayt" — يْ只发"y"音，无元音跟随。',
    color: '#6366F1',
    memory_trick_zh: '记忆法：سُكون = "静止"，圆圈代表"封闭停止"，嘴巴收住 ⊙',
  },
  {
    id: 'shadda',
    symbol: 'ّ',
    name_ar: 'شَدَّة (تَشْديد)',
    name_zh: '沙达 شَدَّة（重叠符/加倍符）',
    name_en: 'Shadda (Tashdid)',
    sound_zh: '字母加倍 — 停顿后重发，相当于两个相同字母',
    sound_en: 'Double consonant — hold then release',
    example_with_ba: 'بَّ',
    example_word: 'محمد',
    example_word_with_harakat: 'مُحَمَّد',
    example_transliteration: 'mu-ḥam-mad',
    example_meaning_zh: '穆罕默德（م加倍发音）',
    example_meaning_en: 'Muhammad (the "m" is doubled)',
    position: 'above',
    tip_zh: '写在字母【上方】，形如w ◌ّ。发音时该字母加倍——先停顿再发。\n例：مُحَمَّد = "Mu-ḥam-mad"，感受"mm"的停顿。\n可与حركة组合：بَّ = "bba"，بِّ = "bbi"',
    color: '#EF4444',
    memory_trick_zh: '记忆法：شَدَّة = "强调/加强"，符号形似两个山峰，代表发音加倍 ∧∧',
  },
  {
    id: 'tanwin_fath',
    symbol: 'ً',
    name_ar: 'تَنوين الفَتْح',
    name_zh: '双法特哈 تنوين فتح（-an结尾）',
    name_en: 'Tanwin Fath',
    sound_zh: '词尾音"-an" — 无定冠词宾格，常写在ا(ألف)之前',
    sound_en: 'End-of-word "-an", indefinite accusative',
    example_with_ba: 'بًا',
    example_word: 'كتاب',
    example_word_with_harakat: 'كِتَابًا',
    example_transliteration: 'ki-taa-ban',
    example_meaning_zh: '（一本）书（宾格）',
    example_meaning_en: 'A book (object in sentence)',
    position: 'above_double',
    tip_zh: '写在词尾上方（两条斜线 ◌ً）。发音词尾加"-an"。\n例：كتاباً = "kitaaban"，شُكْرًا = "shukran"（谢谢！）',
    color: '#8B5CF6',
    memory_trick_zh: '记忆法：两个فَتْحة = 两次"啊" → 连读变"-an"。شُكْرًا你一定能记住！',
  },
  {
    id: 'tanwin_damm',
    symbol: 'ٌ',
    name_ar: 'تَنوين الضَّم',
    name_zh: '双达玛 تنوين ضم（-un结尾）',
    name_en: 'Tanwin Damm',
    sound_zh: '词尾音"-un" — 无定冠词主格（做主语的名词）',
    sound_en: 'End-of-word "-un", indefinite nominative',
    example_with_ba: 'بٌ',
    example_word: 'كتاب',
    example_word_with_harakat: 'كِتَابٌ',
    example_transliteration: 'ki-taa-bun',
    example_meaning_zh: '（一本）书（主格）',
    example_meaning_en: 'A book (subject)',
    position: 'above_double',
    tip_zh: '写在词尾上方（两个钩 ◌ٌ）。发音词尾加"-un"。\n例：كِتَابٌ = "kitaabun"，رَجُلٌ = "rajulun"（一个男人）',
    color: '#06B6D4',
    memory_trick_zh: '记忆法：两个ضَمَّة = 两次"乌" → 连读变"-un"',
  },
  {
    id: 'tanwin_kasr',
    symbol: 'ٍ',
    name_ar: 'تَنوين الكَسْر',
    name_zh: '双卡斯拉 تنوين كسر（-in结尾）',
    name_en: 'Tanwin Kasr',
    sound_zh: '词尾音"-in" — 无定冠词属格（所有格/介词宾语）',
    sound_en: 'End-of-word "-in", indefinite genitive',
    example_with_ba: 'بٍ',
    example_word: 'كتاب',
    example_word_with_harakat: 'كِتَابٍ',
    example_transliteration: 'ki-taa-bin',
    example_meaning_zh: '（一本）书（属格）',
    example_meaning_en: 'A book (possessive/after preposition)',
    position: 'below_double',
    tip_zh: '写在词尾下方（两条斜线 ◌ٍ）。发音词尾加"-in"。\n例：كِتَابٍ = "kitaabin"，فِي بَيْتٍ = "fii baytin"（在一个家里）',
    color: '#EC4899',
    memory_trick_zh: '记忆法：两个كَسْرة在下面 = 两次"衣" → 连读变"-in"',
  },
  {
    id: 'madda',
    symbol: '◌آ',
    name_ar: 'مَدَّة',
    name_zh: '马达 مَدَّة（长音符/长啊）',
    name_en: 'Madda',
    sound_zh: '长"啊"音 — 是فَتْحة的两倍长',
    sound_en: 'Long "aa" — extended alef',
    example_with_ba: 'آ',
    example_word: 'آدم',
    example_word_with_harakat: 'آدَم',
    example_transliteration: 'Aa-dam',
    example_meaning_zh: '亚当（人名）',
    example_meaning_en: 'Adam',
    position: 'above',
    tip_zh: '只写在أ(ألف)上方 → 变成آ。表示长"啊"，是普通فَتْحة时间的两倍。\n例：آدَم = "Aadam"，آسِيا = "Aasia"（亚洲）',
    color: '#F97316',
    memory_trick_zh: '记忆法：مَدَّة = "延长"，符号像一根拉伸的线 ～，声音也拉长。',
  },
]

// ─────────────────────────────────────────────────────────────
//  Helper: group letters by lesson day
// ─────────────────────────────────────────────────────────────
export function getLettersForLesson(dayNumber: number): ArabicLetter[] {
  const map: Record<number, string[]> = {
    1:  ['ا', 'ب', 'ت', 'ث'],
    2:  ['ج', 'ح', 'خ'],
    3:  ['د', 'ذ', 'ر', 'ز'],
    4:  ['س', 'ش'],
    5:  ['ص', 'ض'],
    6:  ['ط', 'ظ'],
    7:  ['ع', 'غ'],
    8:  ['ف', 'ق', 'ك'],
    9:  ['ل', 'م', 'ن'],
    10: ['ه', 'و', 'ي', 'ء'],
  }
  const letters = map[dayNumber] || map[1]
  return letters.map(l => ARABIC_ALPHABET.find(a => a.letter === l)!).filter(Boolean)
}
